version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: quantik_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-quantik}
      POSTGRES_USER: ${POSTGRES_USER:-quantik_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-CHANGE_ME_IN_PRODUCTION}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/quantik.sql:/docker-entrypoint-initdb.d/quantik.sql
    networks:
      - quantik_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-quantik_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PHP with Apache
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quantik_php
    restart: always
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quantik_network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  quantik_network:
    driver: bridge